spring.application.name=sso

# https 설정 (classpath = **/resources)
server.port=1443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=sso1234!!
server.ssl.key-password=sso1234!!
server.ssl.key-alias=java-sso.opentofu.click
server.ssl.key-store-type=PKCS12

# Property Naming Strategy
spring.jackson.property-naming-strategy=SNAKE_CASE

# 로깅 레벨 설정 (배포 & 로컬) journalctl -u java-sts -f
# logging.file.name=/home/sysadmin/log/java-sso-app.log
# logging.file.name=/Users/hyunminlim/Desktop/opentofu/opentofu-log/java-sso-app.log
logging.level.root=DEBUG
logging.level.org.springframework=DEBUG
logging.level.click.opentofu.sso=DEBUG

# 구글 이메일 서버 설정
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=noreply.opentofu@gmail.com
spring.mail.password=hwmwdzhdcngejsvt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# MySQL 데이터베이스 연결 설정
spring.datasource.url=jdbc:mysql://sso.private.mysql:13306/sso?useUnicode=true&characterEncoding=utf8
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=sysadmin
spring.datasource.password=Sysadmin1234!!

# JPA 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.format_sql=true
